import { DomainModuleConfig, DomainModuleKey } from './types';

/**
 * Enterprise Domain Modules Registry
 * Configures all 20 specialized Developer OS modules
 */
export const domainRegistry: Record<DomainModuleKey, DomainModuleConfig> = {
  now: {
    key: 'now',
    name: 'Now',
    description: 'Current focus, location, and active learning',
    iconName: 'clock',
    targetContentType: 'now',
    routePath: '/now',
  },
  uses: {
    key: 'uses',
    name: 'Uses',
    description: 'Hardware, software, network gear, and desk setup',
    iconName: 'terminal',
    targetContentType: 'uses',
    routePath: '/uses',
  },
  resume: {
    key: 'resume',
    name: 'Resume',
    description: 'Curriculum Vitae and professional qualifications',
    iconName: 'fileText',
    targetContentType: 'resume',
    routePath: '/resume',
  },
  career: {
    key: 'career',
    name: 'Career Timeline',
    description: 'Professional engineering history, roles, and milestones',
    iconName: 'server',
    targetContentType: 'career',
    routePath: '/career',
  },
  journal: {
    key: 'journal',
    name: 'Learning Journal',
    description: 'Engineering logs, ops notes, and daily bug fixes',
    iconName: 'fileText',
    targetContentType: 'journal',
    routePath: '/journal',
  },
  notes: {
    key: 'notes',
    name: 'Technical Notes',
    description: 'Atomic technical notes and evergreen knowledge base',
    iconName: 'code',
    targetContentType: 'note',
    routePath: '/notes',
  },
  projects: {
    key: 'projects',
    name: 'Projects',
    description: 'Case studies across Infra, Networking, Web Dev, and AI',
    iconName: 'folder',
    targetContentType: 'project',
    routePath: '/projects',
  },
  certificates: {
    key: 'certificates',
    name: 'Certificates',
    description: 'Verified professional certifications and credentials',
    iconName: 'award',
    targetContentType: 'certificate',
    routePath: '/certificates',
  },
  roadmap: {
    key: 'roadmap',
    name: 'Learning Roadmap',
    description: 'Structured skill progression paths',
    iconName: 'network',
    routePath: '/notes',
  },
  books: {
    key: 'books',
    name: 'Books',
    description: 'Technical reading list and book summaries',
    iconName: 'book',
    targetContentType: 'note',
    routePath: '/notes',
  },
  courses: {
    key: 'courses',
    name: 'Courses',
    description: 'Completed courses and certifications',
    iconName: 'graduationCap',
    targetContentType: 'certificate',
    routePath: '/certificates',
  },
  talks: {
    key: 'talks',
    name: 'Talks & Presentations',
    description: 'Conference talks and slide decks',
    iconName: 'mic',
    targetContentType: 'article',
    routePath: '/articles',
  },
  achievements: {
    key: 'achievements',
    name: 'Achievements',
    description: 'Major engineering milestones and accomplishments',
    iconName: 'trophy',
    targetContentType: 'career',
    routePath: '/career',
  },
  experiments: {
    key: 'experiments',
    name: 'Experiments',
    description: 'Proof of concept prototypes and code labs',
    iconName: 'flaskConical',
    targetContentType: 'project',
    routePath: '/projects',
  },
  'lab-notes': {
    key: 'lab-notes',
    name: 'Lab Notes',
    description: 'GNS3, Cisco, and MikroTik lab configurations',
    iconName: 'router',
    targetContentType: 'note',
    routePath: '/notes',
  },
  timeline: {
    key: 'timeline',
    name: 'Developer Timeline',
    description: 'Unified multi-domain chronological timeline',
    iconName: 'calendar',
    routePath: '/journal',
  },
  'weekly-review': {
    key: 'weekly-review',
    name: 'Weekly Review',
    description: 'Weekly engineering recaps',
    iconName: 'fileText',
    targetContentType: 'journal',
    routePath: '/journal',
  },
  'monthly-review': {
    key: 'monthly-review',
    name: 'Monthly Review',
    description: 'Monthly architectural summaries',
    iconName: 'fileText',
    targetContentType: 'journal',
    routePath: '/journal',
  },
  'year-in-review': {
    key: 'year-in-review',
    name: 'Year in Review',
    description: 'Annual retrospective and growth stats',
    iconName: 'sparkles',
    targetContentType: 'article',
    routePath: '/articles',
  },
  changelog: {
    key: 'changelog',
    name: 'Public Changelog',
    description: 'System updates and release notes',
    iconName: 'gitCommit',
    targetContentType: 'journal',
    routePath: '/journal',
  },
};
